AlternativeVote/urls.py
from django.urls import path

from . import views

app_name = "AlternativeVote"
urlpatterns = [
    path("constituency", views.IndexView.as_view(), name="index"),
    path("constituency/<int:pk>", views.DetailView.as_view(), name="detail"),
    path("constituency/<int:pk>/test", views.testView, name="test"),
    path("constituency/<int:pk>/vote", views.vote, name="vote"),
    path("constituency/<int:pk>/results", views.results, name="results"),
    path("party/<int:pk>", views.party, name="party"),
    path("table", views.national_table, name="national_table"),
]

RealtimeSTV/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views
from Blog.views import webfinger


urlpatterns = [
    path('', views.index, name="index"),
    path("signup", views.signup, name="signup"),
    path("login", views.login, name="login"),

    path('admin/', admin.site.urls),
    path("av/", include("AlternativeVote.urls")),
]

# Blog url stuff
urlpatterns += [
    path('account/', include('Blog.urls')),
]

urlpatterns += [
    path('.well-known/webfinger', webfinger),
    path('blog/', include("Blog.urls"))
]

AlternativeVote/models.py
from django.db import models

# Create your models here.
class Constituency(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Constituencies"


class Party(models.Model):
    name = models.CharField(max_length=200)
    manifesto = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Parties"


class Candidate(models.Model):
    constituency = models.ForeignKey(Constituency, on_delete=models.CASCADE)
    party = models.ForeignKey(Party, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Voter(models.Model):
    ip_address = models.CharField(max_length=100)
    constituency = models.ForeignKey(Constituency, on_delete=models.CASCADE)

    def __str__(self):
        return self.ip_address

class Vote(models.Model):
    voter = models.ForeignKey(Voter, on_delete=models.CASCADE)
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    preference = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.voter.ip_address} - vote {self.preference}"

AlternativeVote/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Constituency, Party, Voter, Candidate, Vote
from django.views import generic
from pprint import pprint
from collections import Counter, namedtuple
from django.urls import reverse
from django.core.cache import cache



def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


class IndexView(generic.ListView):
    template_name = "AlternativeVote/index.html"
    context_object_name = "constituencies"
    def get_queryset(self):
        result = list(Constituency.objects.all())
        return result
    

class DetailView(generic.DetailView):
    model = Constituency
    template_name = "AlternativeVote/detail.html"

def testView(request, pk):
    context = {"word": "what",
               "id": pk}
    return render(request, "AlternativeVote/test.html", context)

def get_candidate_or_none(pk):
    print("PK:", pk)
    try:
        return Candidate.objects.get(pk=pk)
    except:
        return None

def vote(request, pk):
    cache.delete(f"results_page_{pk}")
    cache.delete(f"results_context_{pk}")

    client_ip = get_client_ip(request)
    try:
        Voter.objects.get(ip_address=client_ip).delete()
    except:
        pass
    candidates = {v:k[9:] for k,v in request.POST.items() if v and k.startswith("candidate")}
    print(candidates)
    voter = Voter(
        ip_address=client_ip,
        constituency=Constituency.objects.get(pk=pk),
    )
    voter.save()

    for preference, candidate_key in candidates.items():
        vote = Vote(
            voter=voter,
            candidate=Candidate.objects.get(pk=candidate_key),
            preference=preference[4:]
        )
        vote.save()
    return HttpResponseRedirect(reverse("AlternativeVote:results", args=(pk, )))


def instant_runoff(constituency):
    results = {"rounds":{}}
    candidates = list(constituency.candidate_set.all())
    voters = constituency.voter_set.all()
    ballots = [list(voter.vote_set.all().order_by("preference")) for voter in voters]
    ballots = [[vote.candidate for vote in b] for b in ballots]
    for x in range(len(candidates)-1):
        tally = Counter({candidate:0 for candidate in candidates})

        for card in ballots:
            if card:
                tally[card[0]] += 1
        last_place = tally.most_common()[-1][0]
        for card in ballots:
            if last_place in card:
                card.remove(last_place)
        candidates.remove(last_place)

        results["rounds"][f"round {x+1}"] = {"passed":dict(tally),
                                             "relegated": last_place}
    if tally.most_common()[0][1] > tally.most_common()[1][1]:
        results["winner"] = tally.most_common()[0]
    return results

def first_past_the_post(constituency):
    candidates = constituency.candidate_set.all()
    voters = constituency.voter_set.all()
    tally = Counter({candidate:0 for candidate in candidates})

    #candidate_names = [candidate.name for candidate in candidates]
    for voter in voters:
        if voter.vote_set.all():
            tally[voter.vote_set.all().order_by("preference")[0].candidate] += 1

    results = {"tally": dict(tally),}
    if tally.most_common()[0][1] > tally.most_common()[1][1]:
        results["winner"] = tally.most_common()[0]
    return results

def candidate_duel(candidate_a, candidate_b, voters):
    candidate_a_score = 0
    candidate_b_score = 0
    for voter in voters:
        votes = [vote.candidate for vote in voter.vote_set.order_by("preference")]
        try:
            candidate_a_index = votes.index(candidate_a)
        except:
            candidate_a_index = 999
        try:
            candidate_b_index = votes.index(candidate_b)
        except:
            candidate_b_index = 999
        if candidate_a_index < candidate_b_index:
            candidate_a_score += 1
        elif candidate_b_index < candidate_a_index:
            candidate_b_score += 1

    return candidate_a_score, candidate_b_score

    

def ranked_pairs(constituency):
    candidates = list(constituency.candidate_set.all())
    voters = constituency.voter_set.all()
    score_table = []
    while candidates:
        candidate = candidates.pop()
        for opponent in candidates:
            cp,op = candidate_duel(candidate, opponent, voters)
            score_table.append({candidate: cp, opponent: op})

    candidates = list(constituency.candidate_set.all())
    candidate_totals = Counter({c:0 for c in candidates})
    for duel in score_table:
        a, b = duel.keys()
        if duel[a] > duel[b]:
            candidate_totals[a] += 1
        if duel[b] > duel[a]:
            candidate_totals[b] += 1

    duels = {c:{"duels":[]} for c in candidates}

    def get_winner(a, a_score, b, b_score):
        if a_score > b_score:
            return a.name
        if b_score > a_score:
            return b.name
        return "Draw"

    for duel in score_table:
        items = list(duel.items())
        a, a_score = items[0]
        b, b_score = items[1]
        duels[a]["duels"].append({"opponent": b,
                         "for": a_score,
                         "against": b_score,
                         "winner": get_winner(a, a_score, b, b_score)})
        duels[b]["duels"].append({"opponent": a,
                         "for": b_score,
                         "against": a_score,
                         "winner": get_winner(a, a_score, b, b_score)})

    for c in candidates:
        c.wins = candidate_totals[c]

    results = {"duels": duels}
    if candidate_totals.most_common()[0][1] > candidate_totals.most_common()[1][1]:
        results["winner"] = candidate_totals.most_common()[0]
    return results

def calculate_results(request, pk):
    cached = cache.get(f"results_context_{pk}", None)
    if cached:
        return cached
    constituency = Constituency.objects.get(pk=pk)
    voters = constituency.voter_set.all()
    ballots = []
    #first_past_the_post(ballots, constituency)
    for voter in voters:
        ballots.append([v.candidate.name for v in voter.vote_set.all().order_by("preference")])

    context = {"first_past_the_post":first_past_the_post(constituency),
               "instant_runoff":instant_runoff(constituency),
               "ballots": len(ballots),
               "constituency": constituency,
               "ranked_pairs": ranked_pairs(constituency)}

    
    #response = render(request, "AlternativeVote/results.html", context)
    cache.set(f"results_context_{pk}", context, 86400)
    return context


def results(request, pk):
    cached = cache.get(f"results_page_{pk}", None)
    if cached:
        return cached
    
    context = calculate_results(request, pk)
    response = render(request, "AlternativeVote/results.html", context)
    
    cache.set(f"results_page_{pk}", response, 86400)
    return response


def national_table(request):
    cached = cache.get(f"national_table", None)
    if cached:
        return cached
    
    constituencies = Constituency.objects.all()    
    election_types = ["ranked_pairs", "instant_runoff", "first_past_the_post"]
    counts_table = {et: Counter() for et in election_types}
    results_table = {}

    undecided = Counter()

    for c in constituencies:
        results_table[c] = calculate_results(request, c.id)
        for et in election_types:
            winner = results_table[c][et].get("winner")
            if winner:
                counts_table[et][winner[0].party] += 1
            else:
                undecided[et] += 1

    counts_table = {k:v.most_common() for k,v in counts_table.items()}
    counts_table["undecided"] = dict(undecided)

    response = render(request, "AlternativeVote/table.html", counts_table)
    cache.set("national_table", response)
    return response

def party(request, pk):
    cached = cache.get(f"party_page_{pk}", None)
    if cached:
        return cached
    party = Party.objects.get(pk=pk)
    constituencies = Constituency.objects.all()
    election_types = ["ranked_pairs", "instant_runoff", "first_past_the_post"]
    seats_won = {}
    for c in constituencies:
        result = calculate_results(request, c.id)
        for et in election_types:
            winner = result[et].get("winner")
            if winner:
                if winner[0].party == party:
                    existing = seats_won.get(winner[0])
                    if not existing:
                        seats_won[winner[0]] = {}
                    seats_won[winner[0]][et] = True
    candidates = {"candidates": seats_won,
                  "party": party}
    response = render(request, "AlternativeVote/party.html", candidates)
    cache.set(f"party_page_{pk}", response)
    return response

AlternativeVote/templates/AlternativeVote/detail.html
{% extends 'templates/home/index.html' %}
{% load static %}
{% block pagetitle %} - {{ constituency.name }}{% endblock %}
{% block extrahead %}
    <script src="{% static 'scripts/details.js' %}" />
{% endblock extrahead %}
{% block content %}
<h2>{{ constituency.name }}</h2>
<i>Ranked choice voting: Select as many candidates as you want in order of preference with <b>1</b> behind the highest. You do not have to rank every candidate.</i>
<form action="{% url 'AlternativeVote:vote' constituency.id %}" method="post">
    {% csrf_token %}
    <table>
        {% for candidate in constituency.candidate_set.all %}
            <tr>
                <td>{{ candidate.name }}<br>
                    {{ candidate.party }}</td> 
                <td>
                <select name="candidate{{ candidate.id }}" 
                        id="select{{ forloop.counter }}" 
                        onchange="manage_selection_visibility();"
                        class="candidate_select">
                <option value=""></option>
                {% for c in constituency.candidate_set.all %}
                <option value="vote{{forloop.counter}}" class="option{{ forloop.counter }}">
                    {{forloop.counter}}
                </option>
                {% endfor %}
                </select>
                </td>
            </tr>
        {% endfor %}
    </table>
    <input type="submit" value="Vote"><br>
    <a href="{% url 'AlternativeVote:results' constituency.id %}">Back to results</a>
</form>
{% endblock content %}

AlternativeVote/templates/AlternativeVote/index.html
{% extends 'templates/home/index.html' %}
{% block pagetitle %} - Constituencies{% endblock %}

{% block content %}
<h2>Constituencies</h2>
<ul>
{% for constituency in constituencies %}
<li><a href="{% url 'AlternativeVote:results' constituency.id %}">{{ constituency.name }}</a></li>
{% endfor %}
</ul>
{% endblock content %}

AlternativeVote/templates/AlternativeVote/party.html
{% extends 'templates/home/index.html' %}
{% block pagetitle %} - {{ party }}{% endblock %}

{% block content %}
<h2>{{ party }}</h2>
<h3>Seats won</h3>
<table>
    {% for candidate, election_types in candidates.items %}
    <tr>
        <th>
            Winner
        </th>
        <th>
            FPTP
        </th>
        <th>
            STV
        </th>
        <th>
            RP
        </th>
    </tr>
    <tr>
        <td>
            Seat: <a href="{% url 'AlternativeVote:results' candidate.constituency.id %}">{{candidate.constituency}}</a>
            <br>Candidate: {{ candidate }}
        </td>
        <td>
            {% if election_types.first_past_the_post %}
                x
            {% endif %}
        </td>
        <td>
            {% if election_types.instant_runoff %}
                x
            {% endif %}
        </td>
        <td>
            {% if election_types.ranked_pairs %}
                x
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

AlternativeVote/templates/AlternativeVote/results.html
{% extends 'templates/home/index.html' %}
{% load static %}
{% block pagetitle %} - {{ constituency.name }}{% endblock %}
{% block extrahead %}
    <link rel="stylesheet" href="{% static 'styles/results.css' %}">
    <script src="{% static 'scripts/results.js' %}" />
{% endblock extrahead %}

{% block scripts %}

{% endblock %}

{% block content %}
<h2>{{ constituency.name }}</h2>
{{ ballots }} ballots cast<br><br>

Results using first past the post:<br>
{% if first_past_the_post.winner %}
    {% include 'templates/AlternativeVote/winner.html' with details=first_past_the_post %}
{% else %}
    <h3 class="compact_heading">Winner: No outright winner</h3>
{% endif %}
    <div class="show_hide_bar" id="show_hide_instant_runoff" onclick="show_vote_details('fptp_logic', 'hidden_details')" >
    <u>Show/hide first past the post process</u>
</div><br>
<div class="hidden_details" id="fptp_logic" onclick="show_vote_details('fptp_process', 'hidden_details')" >
    {% include 'templates/AlternativeVote/explainers/fptp.html' with first_past_the_post=first_past_the_post %}
</div>

Results using single transferable vote:<br>
{% if instant_runoff.winner %}
    {% include 'templates/AlternativeVote/winner.html' with details=instant_runoff %}
{% else %}
    <h3 class="compact_heading">Winner: No outright winner</h3>
{% endif %}
<div class="show_hide_bar" id="show_hide_instant_runoff" onclick="show_vote_details('instant_runoff_logic', 'hidden_details')" >
    <u>Show/hide instant runoff process</u>
</div><br>
<div class="hidden_details" id="instant_runoff_logic">
    {% include 'templates/AlternativeVote/explainers/instant_runoff.html' with instant_runoff=instant_runoff %}
</div>

Results using ranked pair voting:<br>
{% if ranked_pairs.winner %}
    {% include 'templates/AlternativeVote/winner.html' with details=ranked_pairs %}
{% else %}
    <h3 class="compact_heading">Winner: No outright winner</h3>
{% endif %}
<div class="show_hide_bar" id="ranked_pair_voting_runoff" onclick="show_vote_details('ranked_pair_voting_logic', 'hidden_details')" >
    <u>Show/hide ranked pair voting process</u>
</div><br>
<div class="hidden_details" id="ranked_pair_voting_logic">
    {% include 'templates/AlternativeVote/explainers/ranked_pair.html' with ranked_pairs=ranked_pairs %}
</div>

<a href="{% url 'AlternativeVote:detail' constituency.id %}">Vote in this election</a><br>

{% endblock content %}

AlternativeVote/templates/AlternativeVote/table.html
{% extends 'templates/home/index.html' %}
{% block pagetitle %} - Seat Distribution{% endblock %}

{% block content %}
<h2>Seat Distribution</h2>
This is how many seats each party would get in parliament according to each system when counting votes cast on this site.
<h3>First past the post</h3>
<table>
    {% for party in first_past_the_post %}
    <tr>
        <td><a href="party/{{party.0.id}}">{{ party.0 }}</a></td>
        <td>{{ party.1 }}</td>
    </tr>
    {% endfor %}
    <tr>
        <td>undecided</td>
        <td>{{ undecided.first_past_the_post }}</td>
    </tr>
</table>
<br>
<br>
<h3>Single Transferable Vote</h3>
<table>
    {% for party in instant_runoff %}
    <tr>
        <td><a href="party/{{party.0.id}}">{{ party.0 }}</a></td>
        <td>{{ party.1 }}</td>
    </tr>
    {% endfor %}
    <tr>
        <td>undecided</td>
        <td>{{ undecided.instant_runoff }}</td>
    </tr>
</table>
<br>
<br>
<h3>Ranked Pairs</h3>
<table>
    {% for party in ranked_pairs %}
    <tr>
        <td><a href="party/{{party.0.id}}">{{ party.0 }}</a></td>
        <td>{{ party.1 }}</td>
    </tr>
    {% endfor %}
    <tr>
        <td>undecided</td>
        <td>{{ undecided.ranked_pairs }}</td>
    </tr>
    </table>
{% endblock content %}

AlternativeVote/templates/AlternativeVote/test.html
hniohohoih<br>
{{id}} - {{ word }}

AlternativeVote/templates/AlternativeVote/winner.html
<h3 class="compact_heading">Winner: <b>{{ details.winner.0.name }} - {{ details.winner.0.party }}</b></h3>
with {{ details.winner.1 }} votes <br>